### ISSUE TITLE
Get GFLOPs

### ISSUE THREAD

**Issue by bearpaw** [apaszke/torch-opCounter#5]
Hi, 

I'm trying to compute the GFLOPs by using this code
```
local sampleInput = torch.randn(1, 3, inputRes, inputRes):cuda()
local total, layer_ops = count_ops(model, sampleInput)
print(string.format('    Total: %.2f GFLOPS', total/10^9))
```

Is it correct to use `total/10^9` to get the GFLOPs? Thanks!

**Comment by apaszke** [comment]
Yeah, G is giga which is 10^9 so I can't see anything wrong with that
